service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    process-photo:
        handler: processPhoto.php
        description: ''
        layers:
            - ${bref:layer.php-74}
    save-labels:
        handler: saveLabels.php
        description: ''
        layers:
            - ${bref:layer.php-74}
    notify-absence:
        handler: notifyAbsence.php
        description: ''
        layers:
            - ${bref:layer.php-74}


# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
